CREATE TABLE course (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL
);

CREATE SEQUENCE course_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE student (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  gender VARCHAR(10) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(10) NOT NULL
);

CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 1;